### ISSUE TITLE
Gamify presentations

### ISSUE THREAD

**Issue by gevans** [LasVegasRubyGroup/user_group_app#2]
Presenters should receive 75% of votes for points. Suggesters should receive 25%. When splitting points, presenters should receive the left over point.

``` feature
Feature: Presentation gamification
  In order to demonstrate that I'm more awesome than anyone else
  As an egotistical user
  I want to be awarded points for presenting and suggesting topics

  Scenario: I'm picked to present for a topic
    Given I have volunteered for "Building Cool Stuff"
    And "Building Cool Stuff" has 21 votes
    When I am selected to present "Building Cool Stuff" at a meetup
    Then I should receive 75%, or 16 points

  Scenario: I suggest a topic
    Given I have suggested a topic "Destroying Lame Stuff"
    And "Destroying Lame Stuff" has 16 votes
    When I "Destroying Lame Stuff" is presented at a meetup
    Then I should receive 25%, or 4 points
```

**Comment by alexpeachey** [comment]
We souls make earn_points! on user that takes a number of points adds them to current points and saves. 

Might help isolate or fix issue. 
Then it is
presenter.earn_points(presenter_points)

**Comment by alexpeachey** [comment]
Fixed it. Basic problem was the spec was broken. But also created earn_points to put push logic to user. Tests pass but I haven't run app to verify creating a meeting assigns the points as expected.

Let's verify that and close.

**Comment by gevans** [comment]
I vote for `User#reward_points!` for the method naming.
